name: Python Click App with Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run format
      run: make format

    - name: Run test
      run: make test

  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Logging to Github registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build and push cli app
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: ghcr.io/hfjohann/nba-guessr:latest
        push: true
